# Generated by Django 3.2.9 on 2021-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
