# Generated by Django 3.2.9 on 2021-12-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211202_1319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
